apiVersion: v2
name: nvidia-gpu-operator
description: Helm chart for deploying NVIDIA GPU Operator
type: application
version: 0.3.0
appVersion: "1.0"
maintainers:
  - name: rh-mobb
dependencies:
  - name: helper-status-checker
    version: 4.4.3
    repository: https://rh-mobb.github.io/validated-pattern-helm-charts/
    condition: helper-status-checker.enabled
