{{- if .Values.platformMetadata.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: efs-from-metadata
  namespace: openshift-cluster-csi-drivers
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: efs-from-metadata
  namespace: openshift-cluster-csi-drivers
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: efs-from-metadata
  namespace: openshift-cluster-csi-drivers
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: efs-from-metadata
subjects:
  - kind: ServiceAccount
    name: efs-from-metadata
    namespace: openshift-cluster-csi-drivers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: efs-from-metadata-read
  namespace: {{ .Values.platformMetadata.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: [{{ .Values.platformMetadata.name | quote }}]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: efs-from-metadata-read
  namespace: {{ .Values.platformMetadata.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: efs-from-metadata-read
subjects:
  - kind: ServiceAccount
    name: efs-from-metadata
    namespace: openshift-cluster-csi-drivers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: efs-from-metadata-storageclass
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: efs-from-metadata-storageclass
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: efs-from-metadata-storageclass
subjects:
  - kind: ServiceAccount
    name: efs-from-metadata
    namespace: openshift-cluster-csi-drivers
{{- end }}
