# Using sub-chart helper-installplan-approver
helper-status-checker:
  approver: true
  enabled: true
  checks:
    - operatorName: advanced-cluster-management
      subscriptionName: advanced-cluster-management
      namespace:
        name: open-cluster-management
      serviceAccount:
        name: "status-checker"
    - operatorName: multicluster-engine
      subscriptionName: multicluster-engine
      namespace:
        name: multicluster-engine
      syncwave: 5
      serviceAccount:
        name: "mce-status-checker"
# acm-operator.v2.13.3
helper-operator:
  enabled: true
  operators:
    advanced-cluster-management:
      operatorgroup:
        create: true
        notownnamespace: false
      enabled: true
      namespace:
        name: open-cluster-management
      subscription:
        channel: release-2.16
        approval: Manual
        operatorName: advanced-cluster-management
        source: redhat-operators
        sourceNamespace: openshift-marketplace
namespaces:
  - name: open-cluster-management
  - name: multicluster-engine

# Sync wave for MultiClusterHub deployment
syncwave: 4

requeueAfterSeconds: 10

# ArgoCD ApplicationSets for spoke cluster management
argocd:
  applications:
  - name: spoke-cluster-config
    annotations:
    helmRepoUrl: https://rh-mobb.github.io/validated-pattern-helm-charts/
    chart: app-of-apps-infrastructure
    project: cluster-config-project
    targetRevision: 0.2.2
    gitRepoUrl: https://github.com/rh-mobb/rosa-cluster-config.git
    adGroup: PFAUTHAD
    # gitPathFile will be constructed dynamically as: {{metadata.labels.environment}}/{{name}}/infrastructure.yaml
    gitPathFile: infrastructure.yaml
    repositories:
    - https://github.com/rh-mobb/rosa-cluster-config.git
    - https://rh-mobb.github.io/validated-pattern-helm-charts/
  - name: spoke-application-ns
    annotations:
    helmRepoUrl: https://rh-mobb.github.io/validated-pattern-helm-charts/
    chart: app-of-apps-application
    project: application-ns-project
    targetRevision: 1.5.8
    gitRepoUrl: https://github.com/rh-mobb/rosa-cluster-config.git
    adGroup: PFAUTHAD
    # gitPathFile will be constructed dynamically as: {{metadata.labels.environment}}/{{name}}/applications-ns.yaml
    gitPathFile: applications-ns.yaml
    repositories:
    - https://github.com/rh-mobb/rosa-cluster-config.git
    - https://rh-mobb.github.io/validated-pattern-helm-charts/
