apiVersion: v2
name: servicemesh-operator-ambient
description: Helm chart for deploying Red Hat OpenShift Service Mesh 3 Operator
icon: https://raw.githubusercontent.com/openshift/console/master/frontend/public/imgs/logos/openshift.svg
type: application
version: 1.3.6
appVersion: "3.0"
dependencies:
  - name: helper-status-checker
    version: 4.4.3
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
    condition: helper-status-checker.enabled
home: https://rh-mobb.github.io/validated-pattern-helm-charts/
maintainers:
  - name: rh-mobb
