namespace: openshift-operators

subscription:
  name: servicemeshoperator3
  channel: stable
  installPlanApproval: Manual
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: ""

operatorGroup:
  create: false

kiali:
  startingCSV: ""

ambient:
  enabled: true
  version: v1.27-latest
  istio:
    name: default
    namespace: istio-system
    version: ""
  cni:
    name: default
    namespace: istio-cni
    version: ""
  ztunnel:
    name: default
    namespace: ztunnel
    version: ""

observability:
  enabled: true
  userWorkloadMonitoring:
    enabled: true

helper-status-checker:
  enabled: true
  approver: true
  checks:
    - operatorName: servicemeshoperator3
      subscriptionName: servicemeshoperator3
      namespace:
        name: openshift-operators
      serviceAccount:
        name: "servicemesh-install-check"
    - operatorName: kiali-operator
      subscriptionName: kiali-ossm
      namespace:
        name: openshift-operators
      serviceAccount:
        name: "kiali-install-check"
