{{- if or .Values.serviceAccount.roleArn .Values.platformMetadata.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    {{- if .Values.serviceAccount.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn }}
    {{- end }}
{{- end }}
