{{- if .Values.ambient.enabled }}
apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: {{ .Values.ambient.istio.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  namespace: {{ .Values.ambient.istio.namespace }}
  profile: ambient
  version: {{ .Values.ambient.istio.version | default .Values.ambient.version }}
  values:
    pilot:
      trustedZtunnelNamespace: {{ .Values.ambient.ztunnel.namespace }}
    meshConfig:
      defaultProviders:
        metrics:
        - prometheus
{{- end }}
