apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.project.name }}
  annotations:
    openshift.io/comments: {{ .Values.project.annotations.comments }}
    openshift.io/description: {{ .Values.project.annotations.description }}
    openshift.io/display-name: {{ .Values.project.annotations.display_name }}
  labels:
    {{- range $key, $value := .Values.project.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- include "namespaces.labels" . | nindent 4 }}
