{{- $sa := .Values.serviceAccount }}
{{- if and $sa $sa.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "namespaces.serviceAccountName" . }}
  namespace: {{ .Values.project.name }}
  labels:
    {{- include "namespaces.labels" . | nindent 4 }}
  {{- with $sa.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ default false $sa.automount }}
{{- end }}
