{{- range .Values.cudnBgpRoutings }}
---
apiVersion: networking.openshift.io/v1beta1
kind: BGPRouting
metadata:
  name: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  network:
    name: {{ .network.name }}
    subnets:
      {{- toYaml .network.subnets | nindent 6 }}
{{- end }}
