apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cudn-bgp.namePrefix" . }}metrics-reader
  labels:
    {{- include "cudn-bgp.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
