apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cudn-bgp.namePrefix" . }}manager-role
  labels:
    {{- include "cudn-bgp.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - infrastructures
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - frrk8s.metallb.io
  resources:
  - frrconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.ovn.org
  resources:
  - clusteruserdefinednetworks
  - routeadvertisements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - patch
  - update
- apiGroups:
  - networking.openshift.io
  resources:
  - cudnbgpconfigs
  - cudnbgproutings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.openshift.io
  resources:
  - cudnbgpconfigs/finalizers
  - cudnbgproutings/finalizers
  verbs:
  - update
- apiGroups:
  - networking.openshift.io
  resources:
  - cudnbgpconfigs/status
  - cudnbgproutings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.openshift.io
  resources:
  - networks
  verbs:
  - get
  - list
  - patch
  - watch
