apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "cudn-bgp.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: {{ include "cudn-bgp.namePrefix" . }}manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cudn-bgp.namePrefix" . }}manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "cudn-bgp.namePrefix" . }}{{ .Values.serviceAccount.name }}
  namespace: {{ include "cudn-bgp.namespace" . }}
