apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    {{- include "cudn-bgp.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: {{ include "cudn-bgp.namePrefix" . }}controller-manager-metrics-service
  namespace: {{ include "cudn-bgp.namespace" . }}
spec:
  ports:
  - name: https
    port: {{ .Values.metricsPort }}
    protocol: TCP
    targetPort: {{ .Values.metricsPort }}
  selector:
    {{- include "cudn-bgp.selectorLabels" . | nindent 4 }}
