apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "cudn-bgp.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "cudn-bgp.namePrefix" . }}{{ .Values.serviceAccount.name }}
  namespace: {{ include "cudn-bgp.namespace" . }}
