apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-creds
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: {{ .Values.awsSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: postgres-creds
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: {{ .Values.awsSecret.key }}
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.awsSecret.key }}
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: {{ .Values.awsSecret.key }}
        property: POSTGRES_DB
