apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maas-db-config
  namespace: {{ .Values.gatewayInfraNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: {{ .Values.awsSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: maas-db-config
  data:
    - secretKey: DB_CONNECTION_URL
      remoteRef:
        key: {{ .Values.awsSecret.key }}
        property: DB_CONNECTION_URL
