apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  name: {{ .Values.model.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,Validate=false
    openshift.io/display-name: {{ .Values.model.displayName | quote }}
    openshift.io/description: {{ .Values.model.description | quote }}
spec:
  modelRef:
    kind: LLMInferenceService
    name: {{ .Values.model.name }}
