apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    opendatahub.io/generated-namespace: "true"
    maas.opendatahub.io/gateway-access: "true"
    opendatahub.io/dashboard: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
