apiVersion: v2
name: deploy-operator
description: Generic chart to install multiple lightweight OLM operators (no operands) via values
type: application
version: 0.2.0
appVersion: "1.0"
dependencies:
  - name: helper-operator
    version: ~1.1.0
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
  - name: helper-status-checker
    version: ~4.4.3
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
    condition: helper-status-checker.enabled
