{{- if .Values.storageCluster.enabled }}
apiVersion: core.libopenstorage.org/v1
kind: StorageCluster
metadata:
  name: {{ .Values.storageCluster.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.storageCluster.syncWave | default "5" | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,Validate=false
    portworx.io/service-account: portworx
    portworx.io/service-type: "portworx-api:LoadBalancer"
    portworx.io/is-openshift: "true"
    portworx.io/is-eks: "true"
    portworx.io/preflight-check: "true"
    portworx.io/portworx-proxy: "false"
    portworx.io/misc-args: {{ .Values.storageCluster.miscArgs | quote }}
spec:
  image: docker.io/portworx/oci-monitor:{{ .Values.storageCluster.imageVersion }}
  imagePullPolicy: Always
  startPort: {{ .Values.storageCluster.startPort | default 17001 }}
  secretsProvider: k8s
  kvdb:
    internal: true
    {{- if .Values.storageCluster.kvdb }}
    enableTLS: {{ .Values.storageCluster.kvdb.enableTLS | default false }}
    {{- end }}
  cloudStorage:
    deviceSpecs:
    {{- range .Values.storageCluster.cloudStorage.deviceSpecs }}
      - {{ . | quote }}
    {{- end }}
    {{- if .Values.storageCluster.cloudStorage.journalDeviceSpec }}
    journalDeviceSpec: {{ .Values.storageCluster.cloudStorage.journalDeviceSpec | quote }}
    {{- end }}
    {{- if .Values.storageCluster.cloudStorage.systemMetadataDeviceSpec }}
    systemMetadataDeviceSpec: {{ .Values.storageCluster.cloudStorage.systemMetadataDeviceSpec | quote }}
    {{- end }}
  {{- if .Values.storageCluster.runtimeOptions }}
  runtimeOptions:
    {{- range $key, $val := .Values.storageCluster.runtimeOptions }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}
  stork:
    enabled: true
    args:
      webhook-controller: "true"
  csi:
    enabled: true
  monitoring:
    telemetry:
      enabled: true
    prometheus:
      exportMetrics: true
  {{- if .Values.storageCluster.autopilot }}
  {{- if .Values.storageCluster.autopilot.enabled }}
  autopilot:
    enabled: true
    providers:
      - name: default
        type: prometheus
        params:
          url: {{ .Values.storageCluster.autopilot.prometheusUrl }}
    env:
      - name: SSL_CERT_DIR
        value: /etc/ssl/certs:/etc/ssl/custom
    volumes:
      - name: autopilot-service-ca
        mountPath: /etc/ssl/custom
        configMap:
          name: autopilot-service-ca
  {{- end }}
  {{- end }}
  {{- if .Values.storageCluster.iamRoleArn }}
  env:
    - name: PX_CLOUD_IDENTITY
      value: {{ .Values.storageCluster.iamRoleArn | quote }}
  workloadIdentity:
    credentials:
      - cloudProvider: aws
        key: eks.amazonaws.com/role-arn
        value: {{ .Values.storageCluster.iamRoleArn | quote }}
  {{- else if .Values.storageCluster.awsCredsSecret }}
  env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          key: aws-key
          name: {{ .Values.storageCluster.awsCredsSecret }}
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: aws-secret
          name: {{ .Values.storageCluster.awsCredsSecret }}
  {{- end }}
  {{- if .Values.storageCluster.ocpDynamicPlugin }}
  ocpDynamicPlugin:
    cacheAgentImage: {{ .Values.storageCluster.ocpDynamicPlugin.cacheAgentImage | quote }}
    pluginImage: {{ .Values.storageCluster.ocpDynamicPlugin.pluginImage | quote }}
  {{- end }}
{{- end }}
