{{- if .Values.agent.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.roleArn }}
  name: {{ template "cloudwatch-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
