apiVersion: v2
name: portworx-operator
description: Helm chart for deploying Portworx Enterprise operator on ROSA HCP with workload identity (IRSA)
type: application
version: 0.2.24
appVersion: "3.6"
dependencies:
  - name: helper-status-checker
    version: 4.4.3
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
    condition: helper-status-checker.enabled
home: https://rh-mobb.github.io/validated-pattern-helm-charts/
maintainers:
  - name: rh-mobb
